# Generated by Django 3.2.5 on 2021-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='NORMAL', max_length=10),
        ),
    ]
